### ISSUE TITLE
lib/components/layout-elements/layout.ex

### ISSUE THREAD

**Issue by Deankinyua** [briankariuki/tremorx#8]
layout.ex line :41: invalid options [default: nil] for slot :inner_block. The supported options are: [:required, :doc, :validate_attrs]

this brings errors while compiling the code

**Comment by briankariuki** [comment]
@Deankinyua What version of phoenix are you using?

**Comment by briankariuki** [comment]
@Deankinyua I've fixed this in version 0.1.1. Let me know if the issue persists after updating to this new version

**Comment by Deankinyua** [comment]
> @Deankinyua What version of phoenix are you using?

1.7.14

**Comment by Deankinyua** [comment]
it is solved i was using the other version of tremorx
